<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ComBE"
    nsURI="ComBE" nsPrefix="ComBE">
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="requirements"/>
      <details key="2" value="components"/>
      <details key="3" value="root"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="id"/>
      <details key="2" value="label"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorSeq">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="behaviortype"/>
      <details key="2" value="behavior"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviortype" lowerBound="1"
        eType="#//BehaviorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" upperBound="-1"
        eType="#//Behavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="int"/>
      <details key="2" value="label"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="behaviortree"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviortree" lowerBound="1"
        eType="#//BehaviorTree" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorseqs" upperBound="-1"
        eType="#//BehaviorSeq" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardComponent" eSuperTypes="#//Component">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="id"/>
      <details key="2" value="label"/>
      <details key="3" value="behaviorseqs"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemComponent" eSuperTypes="#//Component">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="id"/>
      <details key="2" value="label"/>
      <details key="3" value="behaviorseqs"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorTree" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicSequence" eSuperTypes="#//BehaviorTree">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="nodes"/>
      <details key="2" value="child"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//BehaviorTree"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeBranch" eSuperTypes="#//BehaviorTree">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="nodes"/>
      <details key="2" value="children"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//BehaviorTree" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelBranch" eSuperTypes="#//BehaviorTree">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="nodes"/>
      <details key="2" value="children"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//BehaviorTree" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//Operator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardNode" eSuperTypes="#//Node">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="requirement"/>
      <details key="2" value="tracibilitystatus"/>
      <details key="3" value="component"/>
      <details key="4" value="behavior"/>
      <details key="5" value="label"/>
      <details key="6" value="operator"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tracibilitystatus" lowerBound="1"
        eType="#//TracibilityStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" lowerBound="1"
        eType="#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyNode" eSuperTypes="#//Node">
    <eAnnotations source="StrategoTerm.index">
      <details key="1" value="label"/>
      <details key="2" value="operator"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BehaviorType">
    <eLiterals name="StateRealisation" literal="#S"/>
    <eLiterals name="Selection" literal="#L"/>
    <eLiterals name="Event" literal="#E"/>
    <eLiterals name="Guard" literal="#G"/>
    <eLiterals name="IIEvent" literal="#II"/>
    <eLiterals name="IOEvent" literal="#IO"/>
    <eLiterals name="EIEvent" literal="#EI"/>
    <eLiterals name="EOEvent" literal="#EO"/>
    <eLiterals name="Assertion" literal="#A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TracibilityStatus">
    <eLiterals name="None" literal=""/>
    <eLiterals name="Implied" literal="+"/>
    <eLiterals name="Missing" literal="-"/>
    <eLiterals name="Updated" literal="++"/>
    <eLiterals name="Deleted" literal="--"/>
    <eLiterals name="Refinement" literal="+-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="None" literal=""/>
    <eLiterals name="BranchKill" literal="--"/>
    <eLiterals name="Conjunction" literal="&amp;"/>
    <eLiterals name="Disjunction" literal="|"/>
    <eLiterals name="May" literal="%"/>
    <eLiterals name="Reference" literal="=>"/>
    <eLiterals name="Reversion" literal="^"/>
    <eLiterals name="StartNew" literal="^^"/>
    <eLiterals name="Synchronisation" literal="="/>
    <eLiterals name="XOR" literal="XOR"/>
  </eClassifiers>
</ecore:EPackage>
